
language: cpp
dist: xenial
notifications:
  email: false

# Define builds on mulitple OS/compiler combinations. 
# Feel free to add/remove entries from this list.
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - build-essential
            - mesa-common-dev
            - mesa-utils
            - libosmesa6
            - freeglut3-dev
            - cmake
            - libvtk5-dev
            - doxygen
            - libboost-all-dev
            - git

    

before_install:
  - PARENTDIR=$(pwd)
  - mkdir $PARENTDIR/build

install: 
  - cd $PARENTDIR/build
  - cmake -DCMAKE_BUILD_TYPE=Debug $PARENTDIR

script:
  - make
