#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at travis-ci.org
#
#-----------------------------------------------------------------------------


language: cpp
notifications:
  email: false

dist: xenial

#-----------------------------------------------------------------------------

# Save common build configurations as shortcuts, so we can reference them later.
  addons_gcc48: &gcc48
    apt:
      sources: ['ubuntu-toolchain-r-test', 'boost-latest']
      packages: ['libboost1.55-all-dev', 'libboost-program-options1.55-dev', 'g++-4.8', 'gcc-4.8']
  addons_gcc49: &gcc49
    apt:
      sources: ['ubuntu-toolchain-r-test', 'boost-latest']
      packages: ['libboost1.55-all-dev', 'libboost-program-options1.55-dev', 'g++-4.9', 'gcc-4.9']
  addons_gcc5: &gcc5
    apt:
      packages: ['libboost-all-dev', 'libboost-program-options-dev', 'g++-5', 'gcc-5']
  addons_gcc6: &gcc6
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: ['libboost-all-dev', 'libboost-program-options-dev', 'g++-6', 'gcc-6']
  addons_gcc7: &gcc7
    apt:
      packages: ['libboost-all-dev', 'libboost-program-options-dev',]

#-----------------------------------------------------------------------------

addons:
  apt:
    packages:
      - libvtk5-dev
      - cmake
      - doxygen
      - mesa-common-dev
      - mesa-utils
      - libosmesa6
      - libxt-dev
    update: true


matrix:
  include:

    # Linux GCC Builds

    - os: linux
      compiler: linux-gcc48-dev
      addons: *gcc48
      env: CC='gcc-4.8' CXX='g++-4.8' CXXFLAGS='-Wno-return-type' BUILD_TYPE='Dev'
      dist: trusty

    - os: linux
      compiler: linux-gcc49-dev
      addons: *gcc49
      env: CC='gcc-4.9' CXX='g++-4.9' BUILD_TYPE='Dev'
      dist: trusty

    - os: linux
      compiler: linux-gcc5-dev
      addons: *gcc5
      env: CC='gcc-5' CXX='g++-5' BUILD_TYPE='Dev'

    - os: linux
      compiler: linux-gcc6-dev
      addons: *gcc6
      env: CC='gcc-6' CXX='g++-6' BUILD_TYPE='Dev'

    - os: linux
      compiler: linux-gcc7-dev
      addons: *gcc7
      env: CC='gcc-7' CXX='g++-7' BUILD_TYPE='Dev'
      dist: bionic

    - os: linux
      compiler: linux-gcc7-release
      addons: *gcc7
      env: CC='gcc-7' CXX='g++-7' BUILD_TYPE='Release'
      dist: bionic


#-----------------------------------------------------------------------------

before_install:
  - PARENTDIR=$(pwd)
  - mkdir $PARENTDIR/build

install: 
  - cd $PARENTDIR/build
  - cmake -DCMAKE_BUILD_TYPE=Debug $PARENTDIR

script:
  - make

#-----------------------------------------------------------------------------
