#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at travis-ci.org
#
#-----------------------------------------------------------------------------

language: cpp

dist: xenial

#-----------------------------------------------------------------------------

# Save common build configurations as shortcuts, so we can reference them later.
addons_shortcuts:
  addons_gcc48: &gcc48
    apt:
      sources: ['ubuntu-toolchain-r-test', 'boost-latest']
      packages: ['libboost1.55-all-dev', 'libboost-program-options1.55-dev', 'g++-4.8', 'gcc-4.8', 'libvtk5-dev']
  addons_gcc49: &gcc49
    apt:
      sources: ['ubuntu-toolchain-r-test', 'boost-latest']
      packages: ['libboost1.55-all-dev', 'libboost-program-options1.55-dev', 'g++-4.9', 'gcc-4.9', 'libvtk5-dev']

#-----------------------------------------------------------------------------
addons:
  apt:
    packages:
      - libvtk5-dev
      - libopenmpi-dev
      - openmpi-bin
      - cmake
      - doxygen
      - mesa-common-dev
      - mesa-utils
      - libosmesa6
      - libxt-dev
      - libpng-dev
      - libjpeg-dev
      - libxxf86vm1
      - libxxf86vm-dev
      - libxi-dev
      - libxrandr-dev
      - mesa-common-dev
      - mesa-utils-extra
      - libgl1-mesa-dev
      - libglapi-mesa
      

#-----------------------------------------------------------------------------

matrix:
  include:

    # Linux GCC Builds

    - os: linux
      compiler: linux-gcc48-debug
      addons: *gcc48
      env: CC='gcc-4.8' CXX='g++-4.8' CXXFLAGS='-Wno-return-type' BUILD_TYPE='Debug'
      dist: trusty

    - os: linux
      compiler: linux-gcc49-debug
      addons: *gcc49
      env: CC='gcc-4.9' CXX='g++-4.9' BUILD_TYPE='Debug'
      dist: trusty

#-----------------------------------------------------------------------------

install:
  - cmake --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..

script:
  - make VERBOSE=1

#-----------------------------------------------------------------------------