
language: cpp
dist: trusty
notifications:
  email: false

# Define builds on mulitple OS/compiler combinations. 
# Feel free to add/remove entries from this list.
matrix:
  include:
    - os: linux
      addons:
        apt:
          update: true
          packages:
            - git
            - build-essential
            - cmake
            - doxygen
            - mesa-common-dev
            - mesa-utils
            - libosmesa6
            - libxt-dev
            - libpng-dev
            - libjpeg-dev
            - libxxf86vm1
            - libxxf86vm-dev
            - libxi-dev
            - libxrandr-dev
            - mesa-common-dev
            - mesa-utils-extra
            - libgl1-mesa-dev
            - libglapi-mesa

before_install:
  - PARENTDIR=$(pwd)
  - mkdir $PARENTDIR/build

install: 
  - cd $PARENTDIR/build
  - cmake -DCMAKE_BUILD_TYPE=Debug $PARENTDIR
  - ./install-vtk.sh
  - ./install-boost.sh

script:
  - make
