#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at travis-ci.org
#
#-----------------------------------------------------------------------------

language: cpp

dist: xenial


#-----------------------------------------------------------------------------

# Save common build configurations as shortcuts, so we can reference them later.
addons_shortcuts:
  addons_gcc48: &gcc48
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: ['g++-4.8', 'gcc-4.8']
  addons_gcc49: &gcc49
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: ['g++-4.9', 'gcc-4.9']

#-----------------------------------------------------------------------------

addons:
  apt:
    packages:
      - mesa-common-dev
      - mesa-utils
      - freeglut3-dev
      - libosmesa6
      - doxygen
      - cmake

#-----------------------------------------------------------------------------

matrix:
  env:
    global:
      - BOOST_VERSION=1.57.0
      - BOOST_LIB='/usr/local'
      - VTK_VERSION=5.10.1
      - VTK_LIB='/tmp/lib'
      
  include:

    # Linux GCC Builds

    - os: linux
      compiler: 14.04-gcc48-release
      addons: *gcc48
      env: CC='gcc-4.8' CXX='g++-4.8' CXXFLAGS='-Wno-return-type' BUILD_TYPE='Release'
      dist: trusty

    - os: linux
      compiler: 14.04-gcc49-release
      addons: *gcc49
      env: CC='gcc-4.9' CXX='g++-4.9' BUILD_TYPE='Release'
      dist: trusty
      
#-----------------------------------------------------------------------------

install:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir ${VTK_LIB}
  - sudo apt-get update && sudo apt-get install -qq -y libboost-dev
  - bash install-vtk.sh ${VTK_VERSION} ${VTK_LIB}

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DVTK_DIR=${VTK_LIB} ..

script:
  - make VERBOSE=1

#-----------------------------------------------------------------------------